name: CI/CD Release

on:
    push:
        tags:
            - "v*"

jobs:
    release:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build and package the app
              run: |
                  npm install
                  npm run build
                  npm run package-win-ci

            - name: Get app version
              id: package-version
              run: |
                  PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
                  echo ::set-output name=current-version::$PACKAGE_VERSION
              shell: bash

            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Simple Reader v${{ steps.package-version.outputs.current-version }}
                  draft: true
                  prerelease: false

            - name: Upload win-x64 zip to release assets
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: "./bin/win32/x64/Simple Reader-win32-x64.zip"
                  asset_name: Simple.Reader.${{ steps.package-version.outputs.current-version }}.win-x64.zip
                  asset_content_type: application/zip

    release-mac:
        needs: release
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build and package the app (macOS)
              run: |
                  npm install
                  npm run build
                  npm run package-mac

            - name: Get app version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@master

            - name: Get release
              id: get_release
              uses: bruceadams/get-release@v1.2.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload macOS dmg to release assets
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.get_release.outputs.upload_url }}
                  asset_path: "./bin/mac/x64/Simple Reader-${{ steps.package-version.outputs.current-version }}.dmg"
                  asset_name: Simple.Reader.${{ steps.package-version.outputs.current-version }}.mac-x64.dmg
                  asset_content_type: application/x-apple-diskimage

    release-linux:
        needs: release
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build and package the app (Linux)
              run: |
                  npm install
                  npm run build
                  npm run package-linux

            - name: Get app version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@master

            - name: Get release
              id: get_release
              uses: bruceadams/get-release@v1.2.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload Linux AppImage to release assets
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.get_release.outputs.upload_url }}
                  asset_path: "./bin/linux/x64/Simple Reader-${{ steps.package-version.outputs.current-version }}.AppImage"
                  asset_name: Simple.Reader.${{ steps.package-version.outputs.current-version }}.linux-x64.AppImage
                  asset_content_type: application/octet-stream
